### ISSUE TITLE
Failed to download template from github: Cannot read property 'repo' of undefined

### ISSUE THREAD

**Issue by duowb** [sxzz/create#3]
### Describe the bug

```
> create test
√ Pick a template » Library
√ Pick a template » TypeScript

 ERROR  Failed to download template from github: Cannot read property 'repo' of undefined                                                                                                                                          16:47:47

  at /C:/Users/duowe/AppData/Roaming/nvm/v14.19.3/node_modules/@sxzz/create/node_modules/giget/dist/shared/giget.dd19862e.mjs:152:11
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async downloadTemplate (/C:/Users/duowe/AppData/Roaming/nvm/v14.19.3/node_modules/@sxzz/create/node_modules/giget/dist/shared/giget.dd19862e.mjs:151:20)
  at async create (/C:/Users/duowe/AppData/Roaming/nvm/v14.19.3/node_modules/@sxzz/create/dist/chunk-BEWY7M6W.js:114:3)
  at async run (/C:/Users/duowe/AppData/Roaming/nvm/v14.19.3/node_modules/@sxzz/create/dist/chunk-BEWY7M6W.js:38:3)
```

```
 npx giget@latest git@github.com:sxzz/node-lib-starter.git
npx: installed 17 in 4.935s
Error: Failed to download template from registry: request to https://raw.githubusercontent.com/unjs/giget/main/templates/git@github.com:sxzz/node-lib-starter.git.json failed, reason: unable to verify the first certificate
    at file:///C:/Users/duowe/AppData/Roaming/npm-cache/_npx/6520/node_modules/giget/dist/shared/giget.5e7ec864.mjs:158:11
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async downloadTemplate (file:///C:/Users/duowe/AppData/Roaming/npm-cache/_npx/6520/node_modules/giget/dist/shared/giget.5e7ec864.mjs:157:20)
    at async main (file:///C:/Users/duowe/AppData/Roaming/npm-cache/_npx/6520/node_modules/giget/dist/cli.mjs:32:13)
```

```
 npx giget@latest git@github.com:sxzz/node-lib-starter.git
npx: installed 17 in 1.938s
Error: Failed to download template from registry: Failed to download git@github.com:sxzz/node-lib-starter.git template info from https://raw.githubusercontent.com/unjs/giget/main/templates/git@github.com:sxzz/node-lib-starter.git.json: 404 Not Found
    at file:///C:/Users/duowe/AppData/Roaming/npm-cache/_npx/18988/node_modules/giget/dist/shared/giget.5e7ec864.mjs:158:11
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async downloadTemplate (file:///C:/Users/duowe/AppData/Roaming/npm-cache/_npx/18988/node_modules/giget/dist/shared/giget.5e7ec864.mjs:157:20)
    at async main (file:///C:/Users/duowe/AppData/Roaming/npm-cache/_npx/18988/node_modules/giget/dist/cli.mjs:32:13)
```

```
// config.ts

import type { Config } from 'C:/Users/duowe/AppData/Roaming/nvm/v14.19.3/node_modules/@sxzz/create/dist/types'

const config: Config = {
  "git": {
    "add": true
  },
  "templates": [
    {
      "name": "Library",
      "color": "green",
      "children": [
        {
          "name": "TypeScript",
          "color": "#3178c6",
          "url": "git@github.com:sxzz/node-lib-starter.git"
        }
      ]
    },
    {
      "name": "Web App",
      "url": "git@github.com:sxzz/node-lib-starter.git",
      "git": {
        "init": false
      }
    }
  ]
}

export default config

```

### Reproduction

None

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 4.25 GB / 15.71 GB
  Binaries:
    Node: 14.19.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.52)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by duowb** [comment]
[`giget`](https://github.com/unjs/giget/blob/main/src/_utils.ts#L34)
 
Regular parsing error

``` js
const inputRegex = /^(?<repo>[\w.-]+\/[\w.-]+)(?<subdir>[^#]+)?(?<ref>#[\w.-]+)?/;
function parseGitURI(input) {
  const m = input.match(inputRegex)?.groups;
  return {
    repo: m.repo,
    subdir: m.subdir || "/",
    ref: m.ref ? m.ref.slice(1) : "main"
  };
}

parseGitURI('sxzz/node-lib-starter.git');
parseGitURI('git@github.com:sxzz/node-lib-starter.git');

```
